
save_dir: trained_models//nd-efficientnet_lite0_224x224_relu_no_aspect-ration_more_aug
model:
  arch:
    name: OneStageDetector
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [2,4,6]
      activation: ReLU6
    fpn:
      name: PAN
      in_channels: [40, 112, 320]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 96
      feat_channels: 96
      activation: ReLU6
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: data/faces_train/data
    ann_path: data/faces_train/labels.json
    input_size: [224,224] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.98, 1.1]
      stretch: [[1, 1], [1, 1]]
      rotation: 8
      shear: 0
      translate: 0.025
      flip: 0.5
      brightness: 0.2
      contrast: [0.85, 1.15]
      saturation: [0.85, 1.15]
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
  val:
    name: coco
    img_path: data/faces_test/data
    ann_path: data/faces_test/labels.json
    input_size: [224,224] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 2
  batchsize_per_gpu: 128
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.0002
  warmup:
    name: linear
    steps: 300
    ratio: 0.01
  total_epochs: 130
  lr_schedule:
    name: MultiStepLR
    milestones: [35,85,120]
    gamma: 0.1
  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['Human face']
